apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: set-status
spec:
  inputs:
    resources:
      - name: pr
        type: pullRequest
    params:
      - name: status
        type: string
  outputs:
    resources:
      - name: pr
        type: pullRequest
  steps:
    - name: set
      image: ubuntu
      command: ["bash"]
      args:
        - -c
        - |
          set -ex
          cp -r /workspace/pr/ /workspace/output/
          ls -laR /workspace/output
          cat <<EOF > /workspace/output/pr/status/poop.json
          {
            "Label": "poop",
            "State": "$(inputs.params.status)",
            "Desc": "Tekton is running"
          }
          EOF
          ls -laR /workspace/output
